// --- DATA VOUCHER (100 Kode Acak) ---
const VOUCHER_CODES = [
	"X8F9KQ2M",
	"J3N7C5VW",
	"R1T6Y8PL",
	"M4B2V9XC",
	"Z7K3M1NQ",
	"P8W2R5TC",
	"L9J4F6HX",
	"V2C7B3NM",
	"Q5X8Z1KP",
	"T3R9Y2LW",
	"H6F4J8MN",
	"K1P7W5TC",
	"N9M2B4VX",
	"C8V3Z6LQ",
	"X5K9R1PT",
	"J2F7H4MW",
	"B6N3C8VX",
	"L1T5Y9PQ",
	"M7K2J4FN",
	"R8W3P6TC",
	"V4C9B1NX",
	"Z2X7K5MQ",
	"P3T8R1LW",
	"H9F2J6MN",
	"K4P1W7TC",
	"N5M8B2VX",
	"C6V9Z3LQ",
	"X1K4R8PT",
	"J7F3H5MW",
	"B2N6C9VX",
	"L8T1Y4PQ",
	"M3K7J2FN",
	"R9W5P1TC",
	"V6C2B8NX",
	"Z1X4K9MQ",
	"P7T3R6LW",
	"H5F8J1MN",
	"K2P9W4TC",
	"N8M5B7VX",
	"C1V6Z2LQ",
	"X9K2R5PT",
	"J4F1H8MW",
	"B7N9C3VX",
	"L5T6Y1PQ",
	"M2K8J9FN",
	"R4W1P7TC",
	"V8C5B2NX",
	"Z9X3K6MQ",
	"P1T4R8LW",
	"H2F7J5MN",
	"K6P3W9TC",
	"N1M4B8VX",
	"C5V2Z7LQ",
	"X3K8R4PT",
	"J9F5H1MW",
	"B4N1C6VX",
	"L2T9Y5PQ",
	"M8K5J3FN",
	"R1W7P2TC",
	"V9C4B5NX",
	"Z5X1K8MQ",
	"P4T6R9LW",
	"H8F3J2MN",
	"K9P5W1TC",
	"N3M7B4VX",
	"C2V8Z9LQ",
	"X6K1R7PT",
	"J5F9H2MW",
	"B1N4C8VX",
	"L7T2Y6PQ",
	"M5K3J8FN",
	"R2W9P4TC",
	"V1C6B7NX",
	"Z8X5K2MQ",
	"P9T1R3LW",
	"H4F6J9MN",
	"K7P2W8TC",
	"N6M1B5VX",
	"C9V4Z1LQ",
	"X2K7R3PT",
	"J1F8H5MW",
	"B9N2C4VX",
	"L4T7Y8PQ",
	"M6K9J1FN",
	"R5W4P8TC",
	"V3C1B9NX",
	"Z4X8K5MQ",
	"P2T9R6LW",
	"H7F1J4MN",
	"K5P8W2TC",
	"N2M9B6VX",
	"C4V7Z3LQ",
	"X8K5R1PT",
	"J6F2H9MW",
	"B3N5C1VX",
	"L9T4Y2PQ",
	"M1K6J7FN",
	"R7W2P5TC",
	"V5C8B3NX",
	"Z6X9K1MQ",
];

// --- DATA SOAL (200 SOAL NUSANTARA) ---
const questionBank = [
	// Sejarah (1-25)
	{ id: 1, q: "Siapakah tokoh pahlawan yang dikenal sebagai 'Bapak Pendidikan Nasional'?", options: ["Ki Hajar Dewantara", "Ahmad Dahlan", "Bung Hatta"], a: "Ki Hajar Dewantara" },
	{ id: 2, q: "Semboyan 'Bhinneka Tunggal Ika' diambil dari kitab Sutasoma karya?", options: ["Mpu Tantular", "Mpu Prapanca", "Mpu Gandring"], a: "Mpu Tantular" },
	{ id: 3, q: "Lagu kebangsaan Indonesia Raya pertama kali dikumandangkan pada?", options: ["Sumpah Pemuda 1928", "Proklamasi 1945", "Sidang BPUPKI"], a: "Sumpah Pemuda 1928" },
	{ id: 4, q: "Siapa penjahit bendera Merah Putih pertama?", options: ["Fatmawati", "Kartini", "Dewi Sartika"], a: "Fatmawati" },
	{ id: 5, q: "Dimana teks proklamasi kemerdekaan dibacakan?", options: ["Jl. Pegangsaan Timur 56", "Jl. Imam Bonjol 1", "Istana Merdeka"], a: "Jl. Pegangsaan Timur 56" },
	{ id: 6, q: "Kerajaan Budha terbesar di Indonesia adalah?", options: ["Sriwijaya", "Majapahit", "Tarumanegara"], a: "Sriwijaya" },
	{ id: 7, q: "Siapakah yang dikenal sebagai Pahlawan Revolusi?", options: ["Jenderal Ahmad Yani", "Jenderal Sudirman", "Sultan Hamengkubuwono IX"], a: "Jenderal Ahmad Yani" },
	{ id: 8, q: "Sultan Hasanuddin memimpin perjuangan melawan VOC di daerah?", options: ["Makassar", "Ternate", "Maluku"], a: "Makassar" },
	{ id: 9, q: "Siapa penulis buku 'Habis Gelap Terbitlah Terang'?", options: ["R.A. Kartini", "Cut Nyak Dien", "Dewi Sartika"], a: "R.A. Kartini" },
	{ id: 10, q: "Maha Patih Majapahit yang mengucapkan Sumpah Palapa adalah?", options: ["Gajah Mada", "Hayam Wuruk", "Raden Wijaya"], a: "Gajah Mada" },
	{ id: 11, q: "Konferensi Asia Afrika (KAA) pertama dilaksanakan di kota?", options: ["Bandung", "Jakarta", "Yogyakarta"], a: "Bandung" },
	{ id: 12, q: "Perjanjian Linggarjati ditandatangani pada tahun?", options: ["1946", "1945", "1947"], a: "1946" },
	{ id: 13, q: "Agresi Militer Belanda I terjadi pada tahun?", options: ["1947", "1948", "1949"], a: "1947" },
	{ id: 14, q: "Siapa pencipta lagu 'Bagimu Negeri'?", options: ["Kusbini", "Ibu Sud", "Ismail Marzuki"], a: "Kusbini" },
	{ id: 15, q: "Pahlawan yang memimpin perang di Maluku melawan VOC adalah?", options: ["Pattimura", "Imam Bonjol", "Pangeran Antasari"], a: "Pattimura" },
	{ id: 16, q: "Kapan Pancasila lahir?", options: ["1 Juni 1945", "17 Agustus 1945", "1 Oktober 1945"], a: "1 Juni 1945" },
	{ id: 17, q: "Siapa Wakil Presiden pertama RI?", options: ["Moh. Hatta", "Adam Malik", "Sultan HB IX"], a: "Moh. Hatta" },
	{ id: 18, q: "Nama kapal Belanda yang pertama kali mendarat di Banten dipimpin Cornelis de Houtman?", options: ["Mauritius", "Batavia", "Zeven Provincien"], a: "Mauritius" },
	{ id: 19, q: "Apa nama organisasi pemuda pertama di Indonesia?", options: ["Budi Utomo", "Tri Koro Dharmo", "Jong Java"], a: "Budi Utomo" },
	{ id: 20, q: "Siapa pahlawan dari Aceh yang memimpin Perang Sabil?", options: ["Cut Nyak Dien", "Martha Christina Tiahahu", "Dewi Sartika"], a: "Cut Nyak Dien" },
	{ id: 21, q: "Kerajaan Islam pertama di Indonesia adalah?", options: ["Samudera Pasai", "Demak", "Mataram Islam"], a: "Samudera Pasai" },
	{ id: 22, q: "Siapa tokoh yang mengetik teks proklamasi?", options: ["Sayuti Melik", "Sukarni", "B.M. Diah"], a: "Sayuti Melik" },
	{ id: 23, q: "Negara manakah yang pertama kali mengakui kemerdekaan Indonesia secara de jure?", options: ["Mesir", "India", "Palestina"], a: "Mesir" },
	{ id: 24, q: "Siapa Jenderal yang memimpin perang gerilya saat Agresi Militer II?", options: ["Jenderal Sudirman", "Jenderal Gatot Subroto", "Jenderal Nasution"], a: "Jenderal Sudirman" },
	{
		id: 25,
		q: "Apa kepanjangan dari BPUPKI?",
		options: ["Badan Penyelidik Usaha-usaha Persiapan Kemerdekaan Indonesia", "Badan Pembuat Undang-undang Proklamasi Kemerdekaan Indonesia", "Badan Peneliti Utusan Persatuan Kemerdekaan Indonesia"],
		a: "Badan Penyelidik Usaha-usaha Persiapan Kemerdekaan Indonesia",
	},

	// Geografi (26-50)
	{ id: 26, q: "Provinsi apakah yang terletak paling barat di Indonesia?", options: ["Aceh", "Sumatera Utara", "Kepulauan Riau"], a: "Aceh" },
	{ id: 27, q: "Danau vulkanik terbesar di dunia yang ada di Sumatera Utara adalah?", options: ["Danau Toba", "Danau Singkarak", "Danau Maninjau"], a: "Danau Toba" },
	{ id: 28, q: "Gunung tertinggi di Pulau Jawa adalah?", options: ["Gunung Semeru", "Gunung Merapi", "Gunung Slamet"], a: "Gunung Semeru" },
	{ id: 29, q: "Selat yang memisahkan Pulau Jawa dan Pulau Bali adalah?", options: ["Selat Bali", "Selat Sunda", "Selat Madura"], a: "Selat Bali" },
	{ id: 30, q: "Pulau terbesar di Indonesia (secara wilayah administratif NKRI) adalah?", options: ["Papua", "Kalimantan", "Sumatera"], a: "Papua" },
	{ id: 31, q: "Apa nama sungai terpanjang di Indonesia?", options: ["Sungai Kapuas", "Sungai Mahakam", "Sungai Musi"], a: "Sungai Kapuas" },
	{ id: 32, q: "Kota yang dijuluki Kota Khatulistiwa adalah?", options: ["Pontianak", "Samarinda", "Palu"], a: "Pontianak" },
	{ id: 33, q: "Kepulauan Derawan terletak di provinsi?", options: ["Kalimantan Timur", "Sulawesi Utara", "Papua Barat"], a: "Kalimantan Timur" },
	{ id: 34, q: "Wakatobi adalah destinasi selam terkenal di provinsi?", options: ["Sulawesi Tenggara", "Sulawesi Selatan", "Maluku"], a: "Sulawesi Tenggara" },
	{ id: 35, q: "Ibu kota provinsi Maluku Utara adalah?", options: ["Sofifi", "Ternate", "Ambon"], a: "Sofifi" },
	{ id: 36, q: "Gunung Rinjani terletak di pulau?", options: ["Lombok", "Sumbawa", "Flores"], a: "Lombok" },
	{ id: 37, q: "Taman Nasional Lore Lindu ada di provinsi?", options: ["Sulawesi Tengah", "Sulawesi Barat", "Sulawesi Selatan"], a: "Sulawesi Tengah" },
	{ id: 38, q: "Garis khayal yang memisahkan flora fauna tipe Asiatis dengan tipe Peralihan di Indonesia adalah?", options: ["Garis Wallace", "Garis Weber", "Garis Khatulistiwa"], a: "Garis Wallace" },
	{ id: 39, q: "Provinsi termuda ke-38 di Indonesia (pemekaran Papua) adalah?", options: ["Papua Barat Daya", "Papua Pegunungan", "Papua Selatan"], a: "Papua Barat Daya" },
	{ id: 40, q: "Danau Tiga Warna (Kelimutu) berada di pulau?", options: ["Flores", "Sumba", "Alor"], a: "Flores" },
	{ id: 41, q: "Provinsi Bangka Belitung terkenal dengan hasil tambang?", options: ["Timah", "Emas", "Batu Bara"], a: "Timah" },
	{ id: 42, q: "Taman Nasional Ujung Kulon merupakan habitat asli hewan endemik?", options: ["Badak Bercula Satu", "Gajah", "Harimau"], a: "Badak Bercula Satu" },
	{ id: 43, q: "Gunung api aktif yang terletak di Selat Sunda adalah?", options: ["Anak Krakatau", "Gunung Gede", "Gunung Galunggung"], a: "Anak Krakatau" },
	{ id: 44, q: "Pelabuhan penyeberangan dari Pulau Jawa menuju Pulau Bali di Banyuwangi bernama?", options: ["Ketapang", "Gilimanuk", "Bakauheni"], a: "Ketapang" },
	{ id: 45, q: "Kepulauan Raja Ampat saat ini secara administratif berada di provinsi?", options: ["Papua Barat Daya", "Papua Barat", "Papua Tengah"], a: "Papua Barat Daya" },
	{ id: 46, q: "Kota Ambon dijuluki sebagai Kota?", options: ["Musik", "Bunga", "Bahari"], a: "Musik" },
	{ id: 47, q: "Suku Dayak merupakan suku asli yang mendiami pulau?", options: ["Kalimantan", "Sulawesi", "Sumatera"], a: "Kalimantan" },
	{ id: 48, q: "Ibu kota provinsi Lampung adalah?", options: ["Bandar Lampung", "Palembang", "Bengkulu"], a: "Bandar Lampung" },
	{ id: 49, q: "Labuan Bajo adalah pintu masuk utama menuju Taman Nasional?", options: ["Pulau Komodo", "Kepulauan Seribu", "Pulau Bunaken"], a: "Pulau Komodo" },
	{ id: 50, q: "Puncak Jaya Wijaya di Papua dikenal karena terdapat?", options: ["Salju Abadi", "Hutan Hujan Tropis", "Kawah Vulkanik Besar"], a: "Salju Abadi" },

	// Budaya & Seni (51-75)
	{ id: 51, q: "Apa nama tarian tradisional asal Bali yang menceritakan perlawanan Barong terhadap Rangda?", options: ["Tari Barong", "Tari Kecak", "Tari Pendet"], a: "Tari Barong" },
	{ id: 52, q: "Alat musik petik Sasando berasal dari daerah?", options: ["Nusa Tenggara Timur", "Nusa Tenggara Barat", "Maluku"], a: "Nusa Tenggara Timur" },
	{ id: 53, q: "Seni pertunjukan Wayang Kulit sangat erat dengan budaya suku?", options: ["Jawa", "Sunda", "Bali"], a: "Jawa" },
	{ id: 54, q: "Senjata tradisional khas masyarakat Sunda (Jawa Barat) adalah?", options: ["Kujang", "Keris", "Mandau"], a: "Kujang" },
	{ id: 55, q: "Rumah Gadang dengan ciri khas atap melengkung runcing adalah rumah adat dari provinsi?", options: ["Sumatera Barat", "Sumatera Utara", "Riau"], a: "Sumatera Barat" },
	{ id: 56, q: "Tari Saman yang dilakukan dengan gerakan tangan yang cepat dan kompak berasal dari?", options: ["Aceh", "Padang", "Palembang"], a: "Aceh" },
	{ id: 57, q: "Kain tradisional NTT yang ditenun secara manual disebut?", options: ["Tenun Ikat", "Kain Ulos", "Batik Tulis"], a: "Tenun Ikat" },
	{ id: 58, q: "Suku yang terkenal dengan tradisi lompat batu (Fahombo) adalah?", options: ["Suku Nias", "Suku Batak", "Suku Minang"], a: "Suku Nias" },
	{ id: 59, q: "Apa nama alat musik perkusi khas Minahasa (Sulawesi Utara) yang terbuat dari kayu?", options: ["Kolintang", "Angklung", "Gamelan"], a: "Kolintang" },
	{ id: 60, q: "Upacara pembakaran mayat umat Hindu di Bali disebut?", options: ["Ngaben", "Tiwah", "Rambu Solo"], a: "Ngaben" },
	{ id: 61, q: "Lagu daerah 'Rasa Sayange' berasal dari daerah?", options: ["Maluku", "Papua", "Nusa Tenggara Timur"], a: "Maluku" },
	{ id: 62, q: "Tari Piring dimainkan dengan properti piring di tangan, tarian ini berasal dari daerah?", options: ["Minangkabau", "Melayu", "Batak"], a: "Minangkabau" },
	{ id: 63, q: "Alat musik Angklung yang ditetapkan UNESCO sebagai warisan budaya dunia berasal dari provinsi?", options: ["Jawa Barat", "Jawa Tengah", "Banten"], a: "Jawa Barat" },
	{ id: 64, q: "Rumah adat Honai yang terbuat dari kayu dengan atap jerami berbentuk kerucut adalah milik suku di?", options: ["Papua", "Kalimantan Tengah", "Sulawesi Selatan"], a: "Papua" },
	{ id: 65, q: "Senjata tradisional khas suku Dayak adalah?", options: ["Mandau", "Parang Salawaku", "Rencong"], a: "Mandau" },
	{ id: 66, q: "Tari Jaipong diciptakan oleh Gugum Gumbira, seniman yang berasal dari?", options: ["Bandung", "Jakarta", "Yogyakarta"], a: "Bandung" },
	{ id: 67, q: "Kesenian debus yang mempertontonkan kekebalan tubuh berasal dari daerah?", options: ["Banten", "Jawa Tengah", "Madura"], a: "Banten" },
	{ id: 68, q: "Tarian magis pemanggil hujan di Cirebon dan Majalengka disebut?", options: ["Sintren", "Kuda Lumping", "Reog"], a: "Sintren" },
	{ id: 69, q: "Tradisi upacara pemakaman besar besaran di Tana Toraja disebut?", options: ["Rambu Solo", "Pasola", "Sekaten"], a: "Rambu Solo" },
	{ id: 70, q: "Motif batik yang dulunya hanya boleh dipakai oleh raja dan bangsawan keraton adalah?", options: ["Batik Parang", "Batik Mega Mendung", "Batik Kawung"], a: "Batik Parang" },
	{ id: 71, q: "Tari Tor-Tor yang kental dengan unsur magis berasal dari suku?", options: ["Batak Toba", "Minang", "Dayak"], a: "Batak Toba" },
	{ id: 72, q: "Penutup kepala pria Minangkabau yang dilipat-lipat disebut?", options: ["Deta / Saluak", "Blangkon", "Tanjak"], a: "Deta / Saluak" },
	{ id: 73, q: "Saluang adalah alat musik tiup sejenis seruling bambu yang berasal dari provinsi?", options: ["Sumatera Barat", "Jawa Barat", "Sulawesi Selatan"], a: "Sumatera Barat" },
	{ id: 74, q: "Apa nama rumah adat Suku Bugis di Sulawesi Selatan?", options: ["Bola / Saoraja", "Tongkonan", "Limas"], a: "Bola / Saoraja" },
	{ id: 75, q: "Perayaan menyambut Maulid Nabi Muhammad di Yogyakarta dan Surakarta disebut perayaan?", options: ["Sekaten", "Grebeg", "Tahlilan"], a: "Sekaten" },

	// Pengetahuan Umum & Modern (76-100)
	{ id: 76, q: "Bunga nasional Indonesia yang dijuluki Puspa Bangsa adalah?", options: ["Melati Putih", "Anggrek Bulan", "Rafflesia Arnoldii"], a: "Melati Putih" },
	{ id: 77, q: "Burung apa yang menjadi lambang negara Republik Indonesia?", options: ["Garuda", "Elang Jawa", "Cendrawasih"], a: "Garuda" },
	{ id: 78, q: "Ibu Kota Negara (IKN) baru Indonesia yang dibangun di Kalimantan Timur bernama?", options: ["Nusantara", "Jayapura", "Palangkaraya"], a: "Nusantara" },
	{ id: 79, q: "Siapa Presiden ke-3 Republik Indonesia yang juga dikenal sebagai Bapak Teknologi?", options: ["B.J. Habibie", "Abdurrahman Wahid", "Megawati"], a: "B.J. Habibie" },
	{ id: 80, q: "Apa nama satelit pertama yang diluncurkan oleh Indonesia pada tahun 1976?", options: ["Palapa", "Telkom", "Indostar"], a: "Palapa" },
	{ id: 81, q: "Mata uang resmi Republik Indonesia adalah?", options: ["Rupiah", "Ringgit", "Dollar"], a: "Rupiah" },
	{ id: 82, q: "Kode telepon internasional untuk negara Indonesia adalah?", options: ["+62", "+60", "+65"], a: "+62" },
	{ id: 83, q: "Lembaga tinggi negara yang bertugas memeriksa pengelolaan dan tanggung jawab keuangan negara adalah?", options: ["BPK", "KPK", "Mahkamah Agung"], a: "BPK" },
	{ id: 84, q: "Sensus penduduk di Indonesia yang diselenggarakan oleh BPS dilakukan setiap?", options: ["10 Tahun sekali", "5 Tahun sekali", "2 Tahun sekali"], a: "10 Tahun sekali" },
	{ id: 85, q: "Siapa Presiden Indonesia pertama yang dipilih langsung oleh rakyat melalui Pemilu?", options: ["Susilo Bambang Yudhoyono", "Joko Widodo", "Megawati Soekarnoputri"], a: "Susilo Bambang Yudhoyono" },
	{ id: 86, q: "Sesuai aturan terbaru, apa warna dasar plat nomor untuk kendaraan pribadi di Indonesia?", options: ["Putih tulisan Hitam", "Hitam tulisan Putih", "Merah tulisan Putih"], a: "Putih tulisan Hitam" },
	{ id: 87, q: "Situs warisan dunia Candi Borobudur secara administratif terletak di kabupaten?", options: ["Magelang", "Sleman", "Klaten"], a: "Magelang" },
	{ id: 88, q: "Hari Batik Nasional diperingati oleh masyarakat Indonesia setiap tanggal?", options: ["2 Oktober", "21 April", "10 November"], a: "2 Oktober" },
	{ id: 89, q: "Apa nama jembatan sepanjang 5,4 km yang menghubungkan Surabaya dan Pulau Madura?", options: ["Jembatan Suramadu", "Jembatan Ampera", "Jembatan Pasupati"], a: "Jembatan Suramadu" },
	{ id: 90, q: "Lambang Pohon Beringin pada perisai Garuda Pancasila mewakili sila ke-?", options: ["3 (Tiga)", "4 (Empat)", "5 (Lima)"], a: "3 (Tiga)" },
	{ id: 91, q: "Pembalap mobil asal Indonesia pertama yang berhasil membalap di ajang Formula 1 (F1) adalah?", options: ["Rio Haryanto", "Ananda Mikola", "Sean Gelael"], a: "Rio Haryanto" },
	{ id: 92, q: "Seni bela diri asli Indonesia yang sering dipertandingkan di ajang SEA Games dan Asian Games adalah?", options: ["Pencak Silat", "Tarung Derajat", "Merpati Putih"], a: "Pencak Silat" },
	{ id: 93, q: "Bandar Udara Internasional Kualanamu terletak di provinsi?", options: ["Sumatera Utara", "Sumatera Selatan", "Riau"], a: "Sumatera Utara" },
	{ id: 94, q: "Minuman tradisional Indonesia yang menyehatkan seperti beras kencur dan kunyit asam secara umum disebut?", options: ["Jamu", "Wedang", "Badek"], a: "Jamu" },
	{ id: 95, q: "Hingga tahun 2024, jumlah total provinsi di Indonesia adalah?", options: ["38 Provinsi", "34 Provinsi", "37 Provinsi"], a: "38 Provinsi" },
	{ id: 96, q: "Stadion utama dan terbesar di Indonesia yang terletak di Senayan, Jakarta adalah?", options: ["Gelora Bung Karno", "Jakarta International Stadium", "Gelora Bung Tomo"], a: "Gelora Bung Karno" },
	{ id: 97, q: "Apa sebutan resmi untuk Kereta Cepat Jakarta-Bandung?", options: ["Whoosh", "Argo Bromo", "KRL Commuter"], a: "Whoosh" },
	{ id: 98, q: "Sungai terpanjang kedua di Indonesia setelah Kapuas yang terletak di Kalimantan Timur adalah?", options: ["Sungai Mahakam", "Sungai Barito", "Sungai Musi"], a: "Sungai Mahakam" },
	{ id: 99, q: "Provinsi yang wilayahnya mendapatkan otonomi khusus dengan gelar 'Daerah Istimewa' di Pulau Jawa adalah?", options: ["Yogyakarta", "Jakarta", "Banten"], a: "Yogyakarta" },
	{ id: 100, q: "Apa nama laut dangkal yang terletak di antara Pulau Jawa dan Pulau Kalimantan?", options: ["Laut Jawa", "Laut Banda", "Selat Makassar"], a: "Laut Jawa" },

	// Kuliner (101-125)
	{ id: 101, q: "Makanan khas Palembang yang terbuat dari olahan daging ikan dan sagu adalah?", options: ["Pempek", "Tekwan", "Otak-otak"], a: "Pempek" },
	{ id: 102, q: "Sate Lilit yang dagingnya dililitkan pada batang serai atau bambu merupakan makanan khas dari daerah?", options: ["Bali", "Madura", "Padang"], a: "Bali" },
	{ id: 103, q: "Papeda adalah bubur sagu yang menjadi makanan pokok masyarakat di wilayah?", options: ["Papua dan Maluku", "Nusa Tenggara", "Sulawesi"], a: "Papua dan Maluku" },
	{ id: 104, q: "Kerak Telor adalah jajanan tradisional gurih yang berasal dari suku?", options: ["Betawi", "Sunda", "Jawa"], a: "Betawi" },
	{ id: 105, q: "Bika Ambon merupakan kue tradisional berongga yang berasal dari kota?", options: ["Medan", "Ambon", "Makassar"], a: "Medan" },
	{ id: 106, q: "Soto Banjar adalah sajian soto kaya rempah yang berasal dari provinsi?", options: ["Kalimantan Selatan", "Jawa Timur", "Kalimantan Barat"], a: "Kalimantan Selatan" },
	{ id: 107, q: "Ayam Taliwang yang terkenal dengan bumbu pedasnya adalah kuliner khas dari pulau?", options: ["Lombok", "Sumbawa", "Bali"], a: "Lombok" },
	{ id: 108, q: "Mie tebal bercita rasa pedas kari ini dinamakan Mie Aceh. Dari provinsi manakah asalnya?", options: ["Nanggroe Aceh Darussalam", "Sumatera Utara", "Sumatera Barat"], a: "Nanggroe Aceh Darussalam" },
	{ id: 109, q: "Makanan khas Makassar berupa sup daging sapi berdaging atau jeroan adalah?", options: ["Coto Makassar", "Pallubasa", "Sop Konro"], a: "Coto Makassar" },
	{ id: 110, q: "Nasi Liwet yang disajikan dengan sayur labu siam dan suwiran ayam adalah makanan tradisional khas kota?", options: ["Solo", "Yogyakarta", "Bandung"], a: "Solo" },
	{ id: 111, q: "Rendang yang dinobatkan sebagai salah satu makanan terenak di dunia berasal dari kebudayaan suku?", options: ["Minangkabau", "Melayu", "Batak"], a: "Minangkabau" },
	{ id: 112, q: "Seblak merupakan makanan pedas dengan bumbu kencur dan kerupuk basah yang dipopulerkan dari daerah?", options: ["Bandung (Jawa Barat)", "Cirebon", "Garut"], a: "Bandung (Jawa Barat)" },
	{ id: 113, q: "Es Pisang Ijo adalah sajian penutup khas yang disajikan dengan bubur sumsum dari kota?", options: ["Makassar", "Manado", "Kendari"], a: "Makassar" },
	{ id: 114, q: "Lumpia yang berisi rebung, telur, dan daging ayam/udang adalah jajanan khas dari kota?", options: ["Semarang", "Salatiga", "Yogyakarta"], a: "Semarang" },
	{ id: 115, q: "Kue Lontar adalah kue sejenis pie susu yang sangat terkenal di daerah?", options: ["Papua", "Maluku", "Nusa Tenggara Timur"], a: "Papua" },
	{ id: 116, q: "Sate khas yang menggunakan bumbu kacang pekat manis dan sering dijajakan berkeliling adalah?", options: ["Sate Madura", "Sate Padang", "Sate Taichan"], a: "Sate Madura" },
	{ id: 117, q: "Rawon memiliki ciri khas kuah berwarna hitam pekat karena menggunakan bumbu dari biji?", options: ["Kluwek", "Kemiri", "Pala"], a: "Kluwek" },
	{ id: 118, q: "Ayam Betutu adalah sajian ayam berbumbu pekat yang dipanggang lambat, makanan ini khas dari?", options: ["Bali", "Lombok", "Banyuwangi"], a: "Bali" },
	{ id: 119, q: "Surabi khas yang digulung dengan daun pisang dan terkenal dengan sebutan Serabi Notosuman berasal dari?", options: ["Solo", "Bandung", "Cirebon"], a: "Solo" },
	{ id: 120, q: "Karedok adalah makanan yang terbuat dari sayuran mentah bersaus kacang, khas dari daerah?", options: ["Jawa Barat (Sunda)", "Jawa Tengah", "Jawa Timur"], a: "Jawa Barat (Sunda)" },
	{ id: 121, q: "Soto Lamongan memiliki ciri khas taburan bubuk gurih yang terbuat dari kerupuk udang dan bawang putih yang disebut?", options: ["Koya", "Abon", "Bawang Goreng"], a: "Koya" },
	{ id: 122, q: "Pempek selalu disajikan dengan kuah kental berwarna hitam manis pedas yang disebut?", options: ["Cuko", "Kuah Rujak", "Bumbu Petis"], a: "Cuko" },
	{ id: 123, q: "Tempoyak adalah masakan khas Sumatera bagian selatan yang terbuat dari hasil fermentasi buah?", options: ["Durian", "Nangka", "Cempedak"], a: "Durian" },
	{ id: 124, q: "Tinutuan atau yang lebih dikenal dengan Bubur Manado adalah makanan khas dari provinsi?", options: ["Sulawesi Utara", "Sulawesi Selatan", "Sulawesi Tengah"], a: "Sulawesi Utara" },
	{ id: 125, q: "Gudeg adalah sayur nangka muda manis yang merupakan kuliner ikonik dari kota?", options: ["Yogyakarta", "Bantul", "Gunungkidul"], a: "Yogyakarta" },

	// Sejarah & Tokoh 2 (126-150)
	{ id: 126, q: "Siapakah nama asli dari Pangeran Diponegoro?", options: ["Raden Mas Ontowiryo", "Raden Mas Said", "Raden Syahid"], a: "Raden Mas Ontowiryo" },
	{ id: 127, q: "Tuanku Imam Bonjol adalah pahlawan nasional yang memimpin rakyat Sumatera Barat dalam Perang?", options: ["Padri", "Puputan", "Aceh"], a: "Padri" },
	{ id: 128, q: "Pahlawan wanita dari Jawa Barat yang berjuang mendirikan sekolah Keutamaan Istri adalah?", options: ["Dewi Sartika", "R.A. Kartini", "Cut Nyak Meutia"], a: "Dewi Sartika" },
	{ id: 129, q: "Prasasti Yupa peninggalan Kerajaan Kutai Martadipura (kerajaan Hindu tertua) ditulis menggunakan aksara?", options: ["Pallawa", "Kawi", "Brahmi"], a: "Pallawa" },
	{ id: 130, q: "Kerajaan Majapahit mencapai puncak kejayaannya pada masa pemerintahan Raja?", options: ["Hayam Wuruk", "Raden Wijaya", "Jayanegara"], a: "Hayam Wuruk" },
	{ id: 131, q: "Organisasi pergerakan Budi Utomo didirikan oleh mahasiswa STOVIA yang diketuai oleh?", options: ["Dr. Soetomo", "Dr. Cipto Mangunkusumo", "Ki Hajar Dewantara"], a: "Dr. Soetomo" },
	{ id: 132, q: "Kongres Pemuda II yang melahirkan ikrar Sumpah Pemuda diadakan pada tanggal?", options: ["28 Oktober 1928", "20 Mei 1908", "17 Agustus 1945"], a: "28 Oktober 1928" },
	{ id: 133, q: "Siapakah dua tokoh proklamator kemerdekaan yang dijuluki sebagai Bapak Bangsa?", options: ["Soekarno dan Moh. Hatta", "Soekarno dan Syahrir", "Soekarno dan Sudirman"], a: "Soekarno dan Moh. Hatta" },
	{
		id: 134,
		q: "Perundingan yang menghasilkan kesepakatan penyerahan kedaulatan kepada RIS di Den Haag (1949) dinamakan?",
		options: ["Konferensi Meja Bundar", "Perundingan Linggarjati", "Perjanjian Renville"],
		a: "Konferensi Meja Bundar",
	},
	{ id: 135, q: "Pemimpin pertempuran 10 November 1945 di Surabaya yang membakar semangat rakyat dengan pidatonya adalah?", options: ["Bung Tomo", "Gubernur Suryo", "A.W.S. Mallaby"], a: "Bung Tomo" },
	{ id: 136, q: "Untuk mengenang Pertempuran Surabaya, bangsa Indonesia memperingatinya sebagai?", options: ["Hari Pahlawan", "Hari Kesaktian Pancasila", "Hari Kebangkitan Nasional"], a: "Hari Pahlawan" },
	{ id: 137, q: "Peristiwa Gerakan 30 September (G30S) terjadi pada tahun?", options: ["1965", "1966", "1948"], a: "1965" },
	{ id: 138, q: "Operasi militer yang dicetuskan Presiden Soekarno untuk membebaskan Irian Barat dinamakan?", options: ["Trikora", "Dwikora", "Seroja"], a: "Trikora" },
	{ id: 139, q: "Pahlawan nasional asal Maluku yang memimpin perlawanan di Benteng Duurstede Saparua adalah?", options: ["Kapitan Pattimura", "Christina Martha Tiahahu", "Sultan Nuku"], a: "Kapitan Pattimura" },
	{ id: 140, q: "Cut Nyak Meutia adalah pahlawan wanita yang berjuang menentang Belanda di daerah?", options: ["Aceh", "Minangkabau", "Banten"], a: "Aceh" },
	{ id: 141, q: "Panglima Besar TNI pertama yang memimpin perang gerilya menembus hutan meski sedang sakit adalah?", options: ["Jenderal Sudirman", "Jenderal Oerip Soemohardjo", "Jenderal A.H. Nasution"], a: "Jenderal Sudirman" },
	{ id: 142, q: "Tiga Serangkai (Douwes Dekker, Ki Hajar Dewantara, Cipto Mangunkusumo) merupakan pendiri partai bernama?", options: ["Indische Partij", "Sarekat Islam", "Partai Nasional Indonesia"], a: "Indische Partij" },
	{ id: 143, q: "Prasasti Ciaruteun yang menampilkan cap telapak kaki Raja Purnawarman adalah peninggalan kerajaan?", options: ["Tarumanegara", "Salakanagara", "Pajajaran"], a: "Tarumanegara" },
	{ id: 144, q: "Sumpah Palapa diucapkan oleh Gajah Mada pada masa pemerintahan Ratu Majapahit bernama?", options: ["Tribhuwana Tunggadewi", "Dyah Pitaloka", "Ratu Kalinyamat"], a: "Tribhuwana Tunggadewi" },
	{ id: 145, q: "Pemimpin armada niaga Belanda yang pertama kali berlabuh di Banten tahun 1596 adalah?", options: ["Cornelis de Houtman", "Jan Pieterszoon Coen", "Herman Willem Daendels"], a: "Cornelis de Houtman" },
	{ id: 146, q: "Undang-Undang Dasar Negara Kesatuan RI Tahun 1945 disahkan pertama kali oleh PPKI pada?", options: ["18 Agustus 1945", "17 Agustus 1945", "1 Juni 1945"], a: "18 Agustus 1945" },
	{ id: 147, q: "Organisasi Islam Muhammadiyah didirikan di Kampung Kauman Yogyakarta (1912) oleh?", options: ["K.H. Ahmad Dahlan", "K.H. Hasyim Asy'ari", "H.O.S. Tjokroaminoto"], a: "K.H. Ahmad Dahlan" },
	{ id: 148, q: "Organisasi Nahdlatul Ulama (NU) didirikan di Surabaya (1926) oleh tokoh ulama?", options: ["K.H. Hasyim Asy'ari", "K.H. Wahid Hasyim", "K.H. Bisri Syansuri"], a: "K.H. Hasyim Asy'ari" },
	{ id: 149, q: "Perguruan Taman Siswa didirikan pada tanggal 3 Juli 1922 oleh Ki Hajar Dewantara di kota?", options: ["Yogyakarta", "Surakarta", "Jakarta"], a: "Yogyakarta" },
	{ id: 150, q: "Pahlawan nasional dari Sulawesi Selatan yang memimpin perlawanan panjang dalam Perang Makassar adalah?", options: ["Sultan Hasanuddin", "Arung Palakka", "Sultan Baabullah"], a: "Sultan Hasanuddin" },

	// Geografi 2 (151-175)
	{ id: 151, q: "Pulau Bali secara geografis terletak di antara Pulau Jawa dan Pulau?", options: ["Lombok", "Sumbawa", "Madura"], a: "Lombok" },
	{ id: 152, q: "Sungai yang dinobatkan sebagai sungai terpanjang di Pulau Jawa adalah?", options: ["Bengawan Solo", "Sungai Brantas", "Sungai Citarum"], a: "Bengawan Solo" },
	{ id: 153, q: "Gunung api berstatus tertinggi di hamparan Pulau Sumatera adalah Gunung?", options: ["Kerinci", "Leuser", "Dempo"], a: "Kerinci" },
	{ id: 154, q: "Danau tektonik terdalam di Indonesia, bahkan Asia Tenggara, yang terletak di Sulawesi Selatan adalah?", options: ["Danau Matano", "Danau Poso", "Danau Towuti"], a: "Danau Matano" },
	{ id: 155, q: "Kawasan habitat Komodo yang diakui UNESCO sebagai situs warisan dunia terletak di provinsi?", options: ["Nusa Tenggara Timur", "Nusa Tenggara Barat", "Bali"], a: "Nusa Tenggara Timur" },
	{ id: 156, q: "Selat besar yang memisahkan perairan Pulau Sulawesi dengan Pulau Kalimantan adalah Selat?", options: ["Makassar", "Karimata", "Sunda"], a: "Makassar" },
	{ id: 157, q: "Kepulauan Mentawai yang tersohor sebagai destinasi ombak peselancar dunia terletak di provinsi?", options: ["Sumatera Barat", "Sumatera Utara", "Bengkulu"], a: "Sumatera Barat" },
	{ id: 158, q: "Suku Sasak merupakan nama bagi kelompok etnis pribumi yang mendiami Pulau?", options: ["Lombok", "Sumbawa", "Sumba"], a: "Lombok" },
	{ id: 159, q: "Kawasan wisata pasir putih populer seperti Pantai Kuta, Sanur, dan Seminyak berada di provinsi?", options: ["Bali", "Nusa Tenggara Barat", "Jawa Timur"], a: "Bali" },
	{ id: 160, q: "Garis khayal pembatas wilayah fauna tipe Peralihan dengan tipe Australis di timur Indonesia dinamakan?", options: ["Garis Weber", "Garis Wallace", "Garis Lydekker"], a: "Garis Weber" },
	{ id: 161, q: "Kota Palembang yang sangat melekat dengan ikon Jembatan Amperanya, dibelah oleh Sungai?", options: ["Musi", "Batanghari", "Sengatta"], a: "Musi" },
	{ id: 162, q: "Danau Singkarak yang setiap tahunnya menjadi rute ajang balap sepeda internasional (Tour de Singkarak) terletak di?", options: ["Sumatera Barat", "Sumatera Utara", "Riau"], a: "Sumatera Barat" },
	{ id: 163, q: "Gunung Bromo yang pesona kaldera pasirnya sangat diincar wisatawan mancanegara berada di provinsi?", options: ["Jawa Timur", "Jawa Tengah", "Bali"], a: "Jawa Timur" },
	{ id: 164, q: "Pusat pemerintahan (Ibu Kota) dari Provinsi Papua yang terletak di ujung timur teluk adalah kota?", options: ["Jayapura", "Manokwari", "Sorong"], a: "Jayapura" },
	{ id: 165, q: "Di ujung utaranya, Kepulauan Miangas Provinsi Sulawesi Utara berbatasan perairan langsung dengan negara?", options: ["Filipina", "Malaysia", "Timor Leste"], a: "Filipina" },
	{ id: 166, q: "Taman Nasional Tanjung Puting di pesisir Kalimantan Tengah sangat dilindungi karena merupakan pusat rehabilitasi liar bagi satwa?", options: ["Orangutan", "Bekantan", "Gajah Pygmy"], a: "Orangutan" },
	{ id: 167, q: "Jika ditinjau dari luas daratannya, provinsi manakah yang memegang predikat provinsi terkecil di Indonesia?", options: ["DKI Jakarta", "DI Yogyakarta", "Banten"], a: "DKI Jakarta" },
	{ id: 168, q: "Suku Asmat yang ahli mengukir kayu dan Suku Dani yang memiliki tradisi mumi, keduanya berasal dari pulau?", options: ["Papua", "Kalimantan", "Nias"], a: "Papua" },
	{ id: 169, q: "Candi Prambanan dibangun sebagai persembahan untuk Trimurti (Siwa, Brahma, Wisnu) pada era keemasan kerajaan Hindu, yaitu?", options: ["Mataram Kuno", "Majapahit", "Singasari"], a: "Mataram Kuno" },
	{ id: 170, q: "Situs arkeologi Candi Prambanan letaknya berada persis membelah batas administrasi provinsi Jawa Tengah dan?", options: ["DI Yogyakarta", "Jawa Timur", "Jawa Barat"], a: "DI Yogyakarta" },
	{
		id: 171,
		q: "Jajaran punggung pegunungan vulkanik yang membentang dari Aceh hingga Lampung di ujung selatan pulau dinamakan?",
		options: ["Pegunungan Bukit Barisan", "Pegunungan Dieng", "Pegunungan Schwaner"],
		a: "Pegunungan Bukit Barisan",
	},
	{ id: 172, q: "Satu-satunya kota di Indonesia yang secara resmi dijuluki 'Kota Pahlawan' atas pertahanan heroik militannya adalah?", options: ["Surabaya", "Jakarta", "Bandung"], a: "Surabaya" },
	{ id: 173, q: "Berkat sejarah masuknya Islam pertama dan syariatnya, provinsi Nanggroe Aceh Darussalam sangat lekat dengan julukan istimewa?", options: ["Serambi Mekah", "Serambi Madinah", "Bumi Para Wali"], a: "Serambi Mekah" },
	{ id: 174, q: "Kota bersejarah di Jawa Tengah bagian selatan ini tidak hanya dijuluki 'Kota Gudeg', tetapi juga 'Kota Pelajar', yaitu?", options: ["Yogyakarta", "Solo", "Semarang"], a: "Yogyakarta" },
	{ id: 175, q: "Mengingat tingginya intensitas curah hujan bahkan saat musim kemarau, kota Bogor di Jawa Barat mendapat julukan sebagai?", options: ["Kota Hujan", "Kota Kembang", "Kota Angin"], a: "Kota Hujan" },

	// Budaya, Flora & Fauna 2 (176-200)
	{ id: 176, q: "Pakaian adat kuno khas wanita bersiluet longgar transparan yang biasa dipakai di Sulawesi Selatan (terutama suku Bugis) dinamakan?", options: ["Baju Bodo", "Kebaya", "Ulos"], a: "Baju Bodo" },
	{ id: 177, q: "Kain tenun yang selalu dihadirkan dalam kelahiran, perkawinan, maupun kematian pada adat masyarakat Batak disebut?", options: ["Ulos", "Songket", "Sasirangan"], a: "Ulos" },
	{ id: 178, q: "Seni topeng raksasa berkepala singa yang ditunggangi bulu merak (Dadap Merak) merupakan tarian kesenian asli kota?", options: ["Ponorogo", "Banyuwangi", "Madiun"], a: "Ponorogo" },
	{ id: 179, q: "Tari Legong merupakan tarian keraton yang ditarikan oleh beberapa gadis mengenakan kipas atau hiasan mahkota emas, khas dari?", options: ["Bali", "Jawa Timur", "Sunda"], a: "Bali" },
	{ id: 180, q: "Senjata tajam melengkung berukuran pendek mirip arit yang digunakan masyarakat petani hingga perlindungan diri di Jawa Timur adalah?", options: ["Celurit (Madura)", "Kujang", "Rencong"], a: "Celurit (Madura)" },
	{
		id: 181,
		q: "Bunga Bangkai raksasa yang menjadi ikon Kebun Raya Bogor dan endemik asli pegunungan Sumatera bernama latin?",
		options: ["Amorphophallus titanum", "Rafflesia arnoldii", "Phalaenopsis amabilis"],
		a: "Amorphophallus titanum",
	},
	{ id: 182, q: "Tari perang kelincahan dengan properti mandau dan perisai yang menceritakan kegagahan suku Dayak disebut tari?", options: ["Kancet Papatai", "Tari Sajojo", "Tari Piring"], a: "Kancet Papatai" },
	{ id: 183, q: "Tifa merupakan alat musik tabuh dari sebatang kayu berongga yang ditutupi kulit rusa. Instrumen ini khas dari daerah?", options: ["Papua dan Maluku", "Sulawesi dan NTT", "Bali dan Lombok"], a: "Papua dan Maluku" },
	{ id: 184, q: "Dari ratusan bahasa daerah, bahasa dengan penutur asli terbanyak di wilayah teritorial Indonesia adalah?", options: ["Bahasa Jawa", "Bahasa Sunda", "Bahasa Madura"], a: "Bahasa Jawa" },
	{ id: 185, q: "Candi Borobudur didirikan sebagai monumen suci oleh Dinasti/Wangsa pemeluk Buddha Mahayana, yakni?", options: ["Syailendra", "Sanjaya", "Isyana"], a: "Syailendra" },
	{ id: 186, q: "Rumah Panjang yang dapat dihuni puluhan keluarga dan dibuat tinggi dari tanah di pedalaman Kalimantan dinamakan Rumah?", options: ["Betang / Radakng", "Limas", "Gadang"], a: "Betang / Radakng" },
	{ id: 187, q: "Tari Merak yang memperlihatkan keindahan kepakan sayap burung merak melalui kostumnya adalah tarian kontemporer budaya?", options: ["Sunda (Jawa Barat)", "Jawa Tengah", "Banten"], a: "Sunda (Jawa Barat)" },
	{ id: 188, q: "Pertunjukan magis para ksatria menunggang kuda anyaman bambu (sering mengalami kesurupan) dinamakan Kuda Lumping, peninggalan budaya?", options: ["Jawa", "Bali", "Betawi"], a: "Jawa" },
	{ id: 189, q: "Masyarakat etnis sub-Sunda yang teguh menolak modernisasi dan bermukim di pedalaman Pegunungan Kendeng, Banten adalah suku?", options: ["Baduy", "Tengger", "Samin"], a: "Baduy" },
	{ id: 190, q: "Senjata tikam berbilah tunggal asimetris yang diselipkan di pinggang sebagai simbol kehormatan pria di Sulawesi Selatan disebut?", options: ["Badik", "Keris", "Mandau"], a: "Badik" },
	{
		id: 191,
		q: "Kain dengan motif lingkaran putih kecil-kecil yang dibuat dengan mengikat kelereng/koin pada kain sebelum dicelup warna disebut Batik?",
		options: ["Jumputan (Ikat Celup)", "Cap", "Tulis Malam"],
		a: "Jumputan (Ikat Celup)",
	},
	{ id: 192, q: "Festival tarik-menarik dan berpelukan pemuda-pemudi yang hanya diadakan sehari sesudah perayaan Nyepi di Banjar Kaja Sesetan ada di provinsi?", options: ["Bali", "Lombok", "Jawa Timur"], a: "Bali" },
	{ id: 193, q: "Kain Songket indah dari benang emas dan sutra yang menjadi kebanggaan kaum perempuan pesisir Palembang berasal dari budaya era kerajaan?", options: ["Sriwijaya", "Malayu", "Pagaruyung"], a: "Sriwijaya" },
	{ id: 194, q: "Burung Enggang (Rangkong Gading) yang paruhnya sering dijadikan ukiran dan lambang kepemimpinan, amat disucikan oleh etnis Nusantara, yakni suku?", options: ["Dayak", "Asmat", "Mentawai"], a: "Dayak" },
	{
		id: 195,
		q: "Varanus komodoensis, atau naga endemik Kepulauan Sunda Kecil yang dilindungi taman nasional, pada taksonominya adalah karnivora famili kadal atau?",
		options: ["Biawak raksasa", "Buaya", "Iguana raksasa"],
		a: "Biawak raksasa",
	},
	{ id: 196, q: "Karena bentuk bunganya yang memikat, Anggrek Bulan oleh Keputusan Presiden (1990) dinobatkan sebagai bunga perlambang, yaitu?", options: ["Puspa Pesona", "Puspa Langka", "Puspa Hias"], a: "Puspa Pesona" },
	{ id: 197, q: "Pohon endemik hutan tropis yang kayunya amat kuat tahan air tawar (sehingga disebut Kayu Besi/Ulin) adalah identitas asli pulau raksasa?", options: ["Kalimantan", "Jawa", "Papua"], a: "Kalimantan" },
	{ id: 198, q: "Masyarakat petani Hindu di dataran tinggi yang setiap tahunnya melarung sesajen di kawah Gunung Bromo adalah sub-etnis Jawa yang disebut Suku?", options: ["Tengger", "Baduy", "Osing"], a: "Tengger" },
	{ id: 199, q: "Gamelan yang memiliki tangga nada khusus (Pelog dan Slendro pelog) yang mengalun harmonis di tanah Parahyangan dikenal sebagai Gamelan?", options: ["Degung", "Gong Kebyar", "Rindik"], a: "Degung" },
	{
		id: 200,
		q: "Tari Kecak dari Bali dikenal unik karena tidak diiringi alat musik konvensional, melainkan diiringi oleh?",
		options: ["Paduan suara mulut puluhan pria", "Tepukan tangan penari wanita", "Pukulan gendang bambu"],
		a: "Paduan suara mulut puluhan pria",
	},
];
